# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.sbm.mc.sevenroomstoreviewpro: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      application.id: sevenroomstoreviewpro
      auto.offset.reset.config: latest
      security.protocol: 'PLAINTEXT'
      sasl.mechanism: ''
      sasl.jaas.config: ''
      ssl.sslTruststoreLocation: ''
      ssl.sslTruststorePassword: ''
    topics:
      reservation-topic: data-7rooms-reservation
      logs-topic: log-7rooms2revpro-app

  data:
    mongodb:
      uri: mongodb://localhost:27017/SevenRoomsToReviewProApplication
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 6060

sevenroomsApi:
  graviteeUrl: 'https://apm-dev0.sbm.interne/sevenrooms-search/v1/'
  api-key: 78104fa5-022c-4b0d-8795-b91c6e3454c3
  clientId: c902f7eb6c38cb7aa6fa4e806995efbb6948185255d735da5b575e780bc4ee6920983ea58f54e4e7a435ea35ab371574bbb99b1d08c5702fa1cf7dafeedf4076
  clientSecret: bedcc8ae3b05175d3876657ce38e263a1380bd2906c7511236eb0c4e89c9c904efcb6b197e4ef9b145c4b5668baf3d6db76c8c7a15ed5115da2d0db26cfdc5bc
  venueGroupId: ahhzfnNldmVucm9vbXMtc2VjdXJlLWRlbW9yIQsSFG5pZ2h0bG9vcF9WZW51ZUdyb3VwGICAqODizYQJDA

reviewproApi:
  graviteeUrl: 'https://apm-dev0.sbm.interne/reviewpro/v1/'
  api-key: 909bb6e4-8571-450f-b9c8-e6251040c981

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ZWYyNWE3OWMyOTM0NTk5ZThlYTllYmIwODRmOTdmZDgxNmMzN2I4Yjk2YWMwMjI1ZmNmMDQ5NGI5YjEwNTc0NTY0MmFjYmNjZTRkZTFiM2VjY2NlMWUyZTZlNDIxOTk0YTdjODZlZGQwYjZkZjYwMTIxZjZhY2Y1MjJkYTBhMGY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:6060
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
