import { IClient, NewClient } from './client.model';

export const sampleWithRequiredData: IClient = {
  id: 'cd467c90-c5ed-4f11-9c95-4ec6798e2321',
};

export const sampleWithPartialData: IClient = {
  id: 'b179fecd-3e4a-4825-8410-3b0f01562414',
  createdDate: 'dickey um',
  gender: 'unaware',
  salutation: 'witter pianist rejoice',
  title: 'whether floodplain untidy',
  birthdayDay: 13156,
  anniversaryDay: 21043,
  anniversaryMonth: 29598,
  company: 'for somersault',
  email: 'Timothy65@gmail.com',
  phoneNumber: 'conflict yesterday',
  phoneNumberlocale: 'round next badly',
  phoneNumberalt: 'nicely mild dazzling',
  address: 'accommodate savage',
  address2: 'experienced wealthy orderly',
  postalCode: 'aha why',
  isContactPrivate: true,
  isOnetimeGuest: true,
  marketingOptin: false,
  marketingOptints: 'yuck till',
  marketingOptOutts: 'aboard young',
  hasBillingProfile: true,
  privateNotes: 'fatherly substitution',
  tags: 'nor',
  totalCovers: 10601.86,
  totalCancellations: 18586.86,
  totalSpendPerCover: 12604.79,
  totalspendPerVisit: 16679.58,
  avgRating: 29869.36,
  externalUserId: 'trap',
  userId: 'hire curiously metro',
  userName: 'vacantly boo',
  totalOrderCount: 15301,
};

export const sampleWithFullData: IClient = {
  id: 'e86792ca-968e-4161-817a-32247d6e579d',
  clientId: 'after tectonics lavish',
  createdDate: 'even glimmer and',
  updatedDate: 'poke flop',
  deletedDate: 'shore righteously',
  lastname: 'for well-off',
  firstname: 'awkwardly',
  gender: 'glockenspiel',
  salutation: 'responsible vicious incidentally',
  title: 'provided karate',
  birthdayDay: 1129,
  birthdayMonth: 31683,
  birthdayAltMonth: 23286,
  anniversaryDay: 403,
  anniversaryMonth: 13968,
  company: 'kitty rural till',
  email: 'Percy.Hilpert80@gmail.com',
  emailAlt: 'round',
  phoneNumber: 'furthermore soap',
  phoneNumberlocale: 'when geez drat',
  phoneNumberalt: 'fresh',
  phoneNumberaltlocale: 'lawyer hypothermia calculating',
  address: 'prioritise furthermore',
  address2: 'search',
  city: 'New Gilberto',
  postalCode: 'mealy alongside past',
  state: 'gosh oh',
  country: 'United States Minor Outlying Islands',
  isContactPrivate: true,
  isOnetimeGuest: true,
  status: 'reap hence',
  loyaltyId: 'curiously among weekend',
  loyaltyRank: 18171,
  loyaltyTier: 'broadly few modest',
  marketingOptin: false,
  marketingOptints: 'sheepishly',
  marketingOptOutts: 'iterate baa righteously',
  hasBillingProfile: true,
  notes: 'questioningly back ack',
  privateNotes: 'bah yippee so',
  tags: 'parking correctly untidy',
  totalVisits: 28874.81,
  totalCovers: 7678.87,
  totalCancellations: 12588.32,
  totalNoShows: 20324.64,
  totalSpend: 10613.93,
  totalSpendPerCover: 668.27,
  totalspendPerVisit: 31790.45,
  avgRating: 12132.39,
  referenceCode: 'threshold cleverly',
  externalUserId: 'barring',
  venueGroupId: 'this',
  birthdayAltDay: 20296,
  userId: 'likewise requisition woot',
  userName: 'how incidentally',
  totalOrderCount: 23413,
  preferredLanguageCode: 'well-to-do unless afterwards',
};

export const sampleWithNewData: NewClient = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
