import { IReservation, NewReservation } from './reservation.model';

export const sampleWithRequiredData: IReservation = {
  id: '177f9ccc-ff6e-4570-add6-a7dadd9382b6',
};

export const sampleWithPartialData: IReservation = {
  id: '92b51e8b-6fea-471a-abcc-44e740c4dc1e',
  resvId: 'at colour glider',
  created: 'hybridisation quick-witted colorless',
  deleted: 'tally phew',
  venueGroupClientId: 'although',
  venueId: 'um unnecessarily',
  duration: 18612,
  statusDisplay: 'everlasting patiently instead',
  statusSimple: 'wan',
  accessPersistentId: 'hmph upright',
  arrivedGuests: 11022,
  firstname: 'fumbling while ah',
  email: 'Louisa49@gmail.com',
  phoneNumber: 'when jasmine',
  address2: 'amidst',
  postalCode: 'instantly with',
  state: 'whoever supportive pleasing',
  country: 'Saint Martin',
  loyaltyId: 'and ouch by',
  loyaltyRank: 5022,
  loyaltyTier: 'heft whoa representation',
  arrivalTime: 'carefree tooth',
  leftTime: 'discourse',
  clientRequests: 'till',
  costOption: 26072,
  minPrice: 20694,
  rating: 2953,
  problems: 'sneaky academic',
  autoAssignments: 'bivvy complicate across',
  externalId: 'especially grin till',
  referenceCode: 'denominate assumption wrong',
  reservationType: 'esteemed',
  sendreminderSms: true,
  sourceClientId: 'oof blindly given',
};

export const sampleWithFullData: IReservation = {
  id: 'd5e6bf93-9b09-49ee-ac8d-74ae93f1474f',
  resvId: 'till',
  created: 'nor sum opposite',
  updated: 'since boo',
  deleted: 'yuck',
  venueGroupClientId: 'problem leap ugh',
  venueGroupId: 'avenge',
  venueId: 'gee',
  date: 'dribble',
  duration: 16288,
  checkNumbers: 'interestingly',
  shiftCategory: 'worth instead',
  shiftPersistentId: 'quizzically whether quizzically',
  maxGuests: 8041,
  mfratioMale: 8643,
  mfratioFemale: 4539,
  status: 'enlightened revolving',
  statusDisplay: 'cylindrical very',
  statusSimple: 'choreograph since male',
  accessPersistentId: 'provided',
  arrivedGuests: 4592,
  isvip: false,
  bookedby: 'suspiciously object sod',
  clientReferenceCode: 'bitterly greedily',
  lastname: 'hidden',
  firstname: 'prate',
  email: 'Myrna_Reichert30@yahoo.com',
  phoneNumber: 'torn',
  address: 'familiar helpless',
  address2: 'defiantly',
  city: 'Elainachester',
  postalCode: 'handy once',
  state: 'innocently',
  country: 'Switzerland',
  loyaltyId: 'elect',
  loyaltyRank: 20286,
  loyaltyTier: 'suddenly',
  notes: 'optimistically sternly',
  arrivalTime: 'while adulthood as',
  seatedTime: 'carnation motorcar fooey',
  leftTime: 'herbs jealously',
  clientRequests: 'restructuring urgently if',
  comps: 26870,
  compsPriceType: 'warped well-lit viscose',
  costOption: 29839,
  policy: 'textbook',
  minPrice: 8360,
  prePayment: 10487.39,
  onsitePayment: 10313.22,
  totalPayment: 12638,
  paidBy: 'second brr',
  servedBy: 'gelatin',
  rating: 1626,
  problems: 'spicy elated victorious',
  autoAssignments: 'provided villainous',
  externalClientId: 'gah lively ick',
  externalId: 'briskly',
  externalReferenceCode: 'silently sparrow eek',
  externalUserId: 'failing until',
  modifyReservationLink: 'discretion',
  referenceCode: 'shrilly',
  reservationSmsOptin: false,
  reservationType: 'trim quaintly or',
  sendReminderEmail: false,
  sendreminderSms: true,
  sourceClientId: 'busy insult foresee',
  userId: 'silver on',
  userName: 'nudge',
};

export const sampleWithNewData: NewReservation = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
